version: "3.1"
services:
  # golang:
  #   build: ./golang
  #   command: "go run main.go"
  #   ports:
  #     - "8080:8000"


  rpn_proxy:
    build: ./rpn_proxy
    command: flask run --host=0.0.0.0
    networks:
      my-network:
        aliases:
          - flask-app
    ports:
        - 8080:5000

  nginx:
    image: nginx:1.13.7
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

        
networks:
  my-network: